export const Ginyu = {
    id: 'ginyu',
    name: 'Ginyu',
    head_img: '../assets/characters/ginyu/head.png',
    profile_img: '../assets/characters/ginyu/ginyu.webp',
    description: 'Ginyu Force leader, known for his body change technique.',
    height: 'h-120',
    gender: 'male',
    age: 'Unknown',
    role: 'Captain of the Ginyu Force',
    description_extended: [
        "(ギニュー Ginyū), referred to as Captain Ginyu (ギニュー隊長 Ginyū-taichō) by his subordinates, is the strict but loyal captain of the elite mercenary platoon, the eponymous Ginyu Force. Ginyu is an honorable, yet merciless fighter who constantly strikes poses. He possesses the ability to swap bodies."
    ],
    appearance: [
        "In his most commonly seen body, Captain Ginyu is a tall, purple humanoid alien. The top of his head displays prominent veins, similar to that of a human brain. Two black conical horns protrude from the top sides of his head. Ginyu wears a black variant of the Battle Armor that Frieza's forces wear, with lower side guards, black and white wrist bracers, and the addition of the Ginyu Force insignia on the upper left side of the chest plate. He wears black underwear as his lower body armor. Ginyu is equipped with a green Scouter."
    ],
    personality: [
        "Though equally arrogant and merciless in battle, Captain Ginyu is a stark contrast to other notable members of the Frieza Force due to his flamboyant attitude. He is proud of his fighting poses, which he believes promotes camaraderie, and becomes deeply upset when people mock them. He is a strict but caring leader to his eponymous team. During their confrontation with Vegeta, Gohan and Krillin, Ginyu allows the Force to have fun fighting them in his stead while he delivers the Namekian Dragon Balls to Frieza, rather than keeping a battle with Vegeta to himself. He became incredibly furious when learning from Jeice that his three other subordinates were defeated and killed, and shut down Jeice's suggestion of reporting to Frieza in order to save face for both of them. In addition, he was further irritated that the absence of the other members made his and Jeice's two-man pose look less cool. He can still be strict with the Force, though, as he harshly scolds Jeice for allowing Burter and Recoome to lose to Goku and (in the FUNimation dub only) running away from the fight.",
        "Another contrast Ginyu has to the general Frieza Force is his strong sense of honor in combat. He prefers fair fights, a sentiment that has mostly spread to his team due to their preference for playing Rock-Paper-Scissors to divide up opponents, though Ginyu is even more honorable as he reprimands Jeice for interfering in his fight with Goku and even threatens to kill him if he disrupts them further (Goku, taking note of this, insinuates that Ginyu may not be all bad and even capable of redemption).",
        "Ginyu is a very calculating and methodical man, preferring a pragmatic approach in battle. He is noted by his subordinates to always research the mission at hand before acting. He has a very developed understanding of ki and fighting, and surprises Goku in their battle by revealing that he was aware of the Saiyan concealing his true power level and releasing it in short bursts, since Ginyu himself had been concealing his true power. In the anime, during Goku's fight with Frieza, he notes Frieza's body was spontaneously reacting to Goku's power.",
        "Despite his honorable qualities, Captain Ginyu is loyal to Frieza to a fault, being one of the few men who genuinely reveres Frieza and following any order Frieza gives him. He has never attempted to use his Body Change on Frieza, presumably due to his undying loyalty. Even after accidentally swapping bodies with a Namekian Frog, he persevered his predicament in hopes of serving Frieza once again, and after swapping to Tagoma's body, revealed he had prepared a new fighting pose to celebrate his reunion with his boss. In turn, Frieza regards Ginyu and his men highly, and is far more tolerant and forgiving towards him than any of his other subordinates, showing high leniency towards his eccentric personality along with the Force in general (though he is still generally embarrassed by their posing). In an alternate Tournament of Power scenario in Dragon Ball: Sparking! Zero, Frieza chooses to bring the Ginyu Force along as members of Team Universe 7 due to their exemplary teamwork and ability to follow orders. In Dragon Ball FighterZ, Frieza is also conscious of Ginyu's anguish from his time as a frog, and excuses him for refusing to try and change bodies with Cell. Pre-battle interactions between Golden Frieza and a presumably-revived Ginyu Force in Sparking! Zero reveal Frieza's lack of fondness for the poses and his plan to exclude them from his new Frieza Force, with Ginyu and his teammates all in comical protest. Despite his loyalty to Frieza, however, Ginyu nonetheless claimed to Goku that he 'doesn't follow the orders of anyone' when the latter told him to surrender upon exposing his true power level of 180,000."
    ],
    biography: [
        "Like the other members of the Ginyu Force, Ginyu's special powers originated during his childhood.",
        "According to Dragon Ball Z: Super Saiya Densetsu's strategy guide, when Ginyu first learned of his Body Change ability, he swapped bodies with the richest kid in his class, which made him popular with girls but also stupid, and he soon realized that men should compete in terms of strength rather than money. According to this, Ginyu's purple horned body is his original.",
        "According to a drawing by Toyotarou, Ginyu encountered a powerful being of a horned purple species, with whom he switched bodies with, gaining his most well-known body.",
        "Only a few people have seen Ginyu's true form, and Salza is among them. Cooler integrated Ginyu into his Armored Squadron and Salza had to fight him for the leadership of the squadron. Frieza got Ginyu to join his army not long after."
    ]
}

export const Guldo = {
    id: 'guldo',
    name: 'Guldo',
    head_img: '../assets/characters/guldo/head.png',
    profile_img: '../assets/characters/guldo/guldo.webp',
    description: 'Guldo, the psychic member of the Ginyu Force, can stop time.',
    height: 'h-80',
    gender: 'male',
    age: 'Unknown',
    role: 'Mercenary of the Ginyu Force',
    description_extended: [
        "(グルド Gurudo, lit. 'Ghurd') is the smallest and least physically powerful member of the Ginyu Force. Guldo possesses some psychic abilities, including being able to stop time for as long as he can hold his breath; this seems to be one of the primary reasons he has attained membership to the Ginyu Force. In battle, Guldo is cowardly, and desperate, resorting to different tactics to defeat his enemies."
    ],
    appearance: ["Guldo is a short round alien with light green skin and four eyes (two small ones located like a human's eyes and two much larger eyes located at the sides of his head). He wears a white variant of the regular custom armor Frieza's army wears but does not carry a scouter due to his head structure. Being a member of the Ginyu Force, he has the Ginyu Force symbol on one of his armor's chest plates."],
    personality: [
        "Guldo displays a strong hatred towards Saiyans, especially Vegeta due to negative past conflicts between the two (only shown in the original anime). He has little respect for them as warriors. Guldo especially shows his desire to destroy his hated adversary when he has to play Rock-Paper-Scissors with Recoome, Jeice and Burter and hopes to win so he can crush Vegeta after all these years of waiting. Guldo seems to have an inferiority complex, being the weakest member, and becomes cowardly and desperate when things do not go his way, sometimes resorting to moves and tactics he has not used in a long time. He is also quite out of shape. Guldo is very proud of his position on the Ginyu Force and does not want to be kicked off the team. Guldo is noted to have a nasty personality, as he planned on eating Gohan and Krillin after skewering them. He also shows a sadistic side by tormenting he two after he had paralyzed them. He is also rather perverted, as he used his powers to look up girls' skirts as a child."
    ],
    biography: [
        "Like the other members of the Ginyu Force, Guldo's special powers originated during his childhood. He realized he had psychic powers as a child and caused mischief like lifting up girls' skirts and stealing whatever toys he wanted.",
        "At some point Guldo became a part of the Frieza Force. Guldo was the last member to join the Ginyu Force, in his membership test he had to fight against Burter, Jeice, Recoome, and Ginyu to see if he was worthy to join. He fought alongside a partner (as new recruits were allowed one helper) and managed to prove his worth, thus being given membership.",
        "After he became a member of the Ginyu Force, it is shown in an anime flashback that Guldo has heavy loathing of Vegeta after the Saiyan Prince insulted him by saying that he suffers from bad breath (Vegeta says he does not understand why Frieza put a 'four eyes frog face' like him on the Ginyu Force in the Ocean dub, and Vegeta calls him a 'four eyed freak' in the Funimation dub). Guldo was about to strike when Frieza interfered, asking Vegeta to help him conquer a planet and disgracing Guldo's judgment. This causes Guldo to hold a grudge against Vegeta.",
        "In Dragon Ball: Raging Blast 2, it is revealed that Guldo is not against joining Cooler's Armored Squadron as he says 'If I do well, this could be my chance to join the Armored Squad...' in his pre-match dialog when facing Cooler.",
        "At least a year before they went to Namek, Guldo was invited to join the Ginyu Fitness Club, but he declined and decided to go on a Chili Burger diet. This decision would come back to haunt him later as it proved to cost him stamina."
    ]
}

export const Jeice = {
    id: 'jeice',
    name: 'Jeice',
    head_img: '../assets/characters/jeice/head.png',
    profile_img: '../assets/characters/jeice/jeice.webp',
    description: 'Jeice, the red-skinned warrior, is known for his Crusher Ball attack.',
    height: 'h-100',
    gender: 'male',
    age: 'Unknown',
    role: 'Mercenary of the Ginyu Force',
    description_extended: [
        "(ジース Jīsu, lit. 'Jheese') is a member of the Ginyu Force, acting as Ginyu's second in command and fighting partner of Burter. Being a red-skinned alien humanoid in appearance, Captain Ginyu best describes him as an extremely flamboyant and showy white-haired mutant. Nicknamed the 'Red Magma', he pairs with his best friend Burter for combination attacks, such as the Purple Comet Attack."
    ],
    appearance: [
        "Jeice is of average height compared to other members of the Ginyu Force, such as the tallest member Burter. He has a slender build and bright red skin, green eyes, a small nose, long white hair that extends to his hips, bangs down his forehead, and white eyebrows. He wears a white variant of the regular Battle Armor that most soldiers in Frieza's army wears, but due to being a member of the Ginyu Force, he has a small Ginyu Force inspired logo located on one of his Battle Armor chest plates. He wears a black jumpsuit with sleeves under his armor, with white gloves and boots, and a green scouter.",
        "In Dragon Ball: The Return of Son Goku and Friends!, Vegeta has a flashback in which Jeice lacks the black jumpsuit top and wears nothing on his upper body under his armor."
    ],
    personality: [
        "Like the rest of the Ginyu Force, he is eccentric and loves to pose. Jeice is arrogant and has a tendency to look down on opponents, he is cowardly however as he ran away when he realized he was outmatched. He is dishonorable, as he was willing to attack Goku when his back was turned and had no problems using dirty tactics to gain an advantage. He seems to be somewhat of a narcissist as he was annoyed by the dirt in his hair and had a rivalry with Salza over who looked more attractive. Although he is very cruel, he is not without compassion as the death of his comrades left him horrified. Likewise, he shares a close bond with Burter, as their attacks are usually synchronized, and they respect each other's abilities. He holds his captain in a high regard, coming to his aid without hesitation, always listening to his opinion and boasts of his power in comparison to others. Captain Ginyu seems to return this sentiment, as despite being annoyed with his subordinate's tendency to speak the obvious, his somewhat cowardly behavior and the interference with his fight. Ginyu usually defends him and made Jeice his right-hand man, implying he holds great trust in Jeice."
    ],
    biography: [
        "Jeice is from a planet located in the same planetary system as Salza's home planet, Coola No. 98. Also, Dragon Ball Z: Budokai Tenkaichi 2 states that Jeice and Salza are of the same race. Like the other members of the Ginyu Force, Jeice's special powers originated during his childhood: Jeice was a pitcher in the Galactic Little League, and it is there that he developed the Crusher Ball as his special technique. Soon, while Salza became the leader of Cooler's Armored Squadron, Jeice was recruited in the Ginyu Force led by Captain Ginyu. Jeice has a rivalry with Salza, the two arguing about things like who is the better fighter and who is better looking."
    ]
}

export const Burter = {
    id: 'burter',
    name: 'Burter',
    head_img: '../assets/characters/burter/head.png',
    profile_img: '../assets/characters/burter/burter.webp',
    description: 'Burter, known as the fastest in the universe, is a member of the Ginyu Force.',
    height: 'h-130',
    gender: 'male',
    age: 'Unknown',
    role: 'Mercenary of the Ginyu Force',
    description_extended: [
        '(バータ Bāta, lit. "Butta") is the fastest member of the mercenary platoon known as the Ginyu Force. Being nicknamed the "Blue Hurricane", he often performs combo attacks with Jeice, such as the Purple Comet Hurricane. He is very arrogant, boastful, and tends to talk down to his opponents.'
    ],
    appearance: ["Burter is the tallest member of the Ginyu Force, towering over the other members. He is a hybrid of a reptile and an alien with blue skin, red eyes without pupils and many small spots on his body as well as a light orange plate with a segmented pattern on his head, tubular ears and no nose. He wears a black variant of the usual uniform most of Frieza's army wears but, due to being a member of the Ginyu Force, has a small logo located on one of his Battle Armor chest plates. Like many other members of Frieza's army, he wears a green scouter."],
    personality: [
        "Burter is very proud of his speed, claiming that he's the fastest in the universe, which led to him dubbing himself the 'Blue Hurricane'. Despite Frieza being much faster than him, Burter still calls himself the fastest in the universe, which indicates that he is either arrogant enough to make such a boast despite knowing that Frieza is much faster, or deluded enough to think that he is faster than Frieza. After Guldo is killed by Vegeta, Burter, Recoome, and Jeice are annoyed that their poses will be messed up since they are missing a member. When Recoome is defeated by Goku, he is extremely surprised. He becomes very annoyed when Goku proves himself to be faster.",
        "Burter is good friends with fellow Ginyu Force member Jeice, with the two performing combined attacks on their enemies. Burter seems to be the strategist of the team when Ginyu is not around, which is shown when he comes up with the plan to have Jeice distract Goku with his Crusher Ball while he (Burter) attacks Goku from behind.",
        "Like the other members of the Ginyu Force, Burter is shown to be a rather comical character by doing poses, playing Rock-Paper-Scissors to see who will fight who, and betting Candy over fights."
    ],
    biography : [
        "Like the other members of the Ginyu Force, Burter's special powers originated during his childhood: Burter's mother was very strict, making him do all the household chores and slapping him if he was late preparing dinner; because of this, he became the 'fastest in the universe'. He soon became a member of Frieza's elite mercenary platoon, the Ginyu Force: Burter is the self-proclaimed 'Azure Typhoon' (or 'Blue Hurricane', in the Dragon Ball manga and video games), and fancies himself as the fastest being in the universe.",
        "While facing the Z Fighters on Namek, in the Funimation dub, Burter mentions that he has defeated hundreds of Saiyans. In the Ocean Group dubs, Captain Ginyu mentions that Burter was once a baseball champion (a 'great center fielder')."
    ]
}

export const Recoome = {
    id: 'recoome',
    name: 'Recoome',
    head_img: '../assets/characters/recoome/head.png',
    profile_img: '../assets/characters/recoome/recoome.webp',
    description: 'Recoome, the giant warrior of the Ginyu Force, is known for his flamboyant style.',
    height: 'h-130',
    gender: 'male',
    age: 'Unknown',
    role: 'Mercenary of the Ginyu Force',
    description_extended: [
        "(リクーム Rikūmu) is a member of the Ginyu Force. He is the most flamboyant member as he is seen striking poses more often in battle than Captain Ginyu himself and generally behaving in a deceptively goofy manner."
    ],
    appearance: ["Recoome is very tall and muscular and is distinctly human in appearance. He has shaggy orange hair, beady eyes, no visible eyebrows, and a cleft chin. He wears a green scouter on his left eye, a white Ginyu Force variant of the Battle Armor with a short black jumpsuit under it, white gloves and white boots. On one of his chestplates he has the Ginyu Force's symbol."],
    personality: [
        "Recoome is the most flamboyant member of the Ginyu Force, doing poses even more than Captain Ginyu himself. He is a very comical character, betting Candy over fights and playing Rock-Paper-Scissors to see who will fight who. Although he appears quite brutish and simple, Recoome is fairly intelligent, not to mention sadistic, taking great joy in the suffering of his foes. Unlike the other members of the Ginyu Force, Recoome's personality lingers more towards that of a dim-witted bully. This can be seen as he greatly enjoys toying with his opponents and drawing them in with taunts. In the uncut version, he is also shown to be very crass when it comes to taunting his opponents, as evident when he flips Goku off, mocking his power level based on his scouter reading, furthering the bully persona. Despite his mean-streak, he seems to be very close to his comrades, especially to Guldo, as he is constantly cheering him up in battle and is shocked by his death. He is also the most ostentatious and energetic of the group; almost always striking poses and getting in other people's faces, and also seeming to never take his fights as seriously as the other members. Despite his crassness, he is somewhat effeminate, being very goofy and having practiced ballet as a child. In spite of his cruelty, he does seem to respect those who continue to fight despite the odds, as seen with his apparent admiration toward Gohan for continuing to try and take him on. Recoome also seems to like foes who fight dirty and give him some trouble, as he commented that he liked Vegeta's penchant for sneak attacks."
    ],
    biography: [
        "Like the other members of the Ginyu Force, Recoome's special powers originated during his childhood: Recoome practiced dance, which is how he got his agility and various battle poses. Recoome was later recruited in the Ginyu Force."
    ]
}

export const Frieza = {
    id: 'frieza',
    name: 'Frieza',
    head_img: '../assets/characters/frieza/head.png',
    profile_img: '../assets/characters/frieza/frieza.png',
    description: 'Frieza, the tyrant of the universe, is known for his ruthless ambition and power.',
    height: 'h-110',
    gender: 'male',
    age: 'Unknown',
    role: 'Leader of the Ginyu Force',
    description_extended: [
        "(フリーザ Furīza, lit. 'Freeza') is a major antagonist in the Dragon Ball franchise. He is the descendant of Chilled, the younger son of King Cold, the younger brother of Cooler and the father of Kuriza.",
        "Inheriting his father's imperialist army and rising to power as the emperor of Universe 7 at a young age, Frieza quickly established himself as a ruthless tyrant, feared across the universe for his unparalleled cruelty and power. Ever since his invasion of Namek, Frieza has been the series' most recurring villain, clashing with his archnemesis Goku and his allies on several occasions, becoming even more powerful every time.",
        "Frieza is primarily responsible for the Genocide of the Saiyans and serves as the main antagonist of the overarching Frieza and Golden Frieza sagas, as well as a villainous protagonist during the Universe Survival Saga.",
    ],
    appearance: [
        "Frieza possesses an entire range of transformations, each one being quite different than the others. It is implied by Vegeta and Frieza himself in the series that Frieza's fourth, most powerful form is actually his original form, with the other three being forms that merely suppress his enormous power instead of making him stronger. Frieza later outright confirms this while fighting the main protagonist, Goku. All of his forms seem to revolve around both western and Japanese concepts of demons.",
        "In his first form, Frieza usually wears a standard armor of his army, consisting of a purple body suit with yellow shoulder guards. He also appears to wear black shorts. He also occasionally wears a red scouter. When in his true natural form, Frieza wears his race's Bio Suit. When in his Mecha form, his body is equipped with a permanent Cosmic Suit. In the Universe Survival Saga, he has a halo on his head due to being dead, although this is removed after the tournament due to Whis restoring his life for 'good behavior.'"
    ],
    personality: [
        "Unlike most primary antagonists, Frieza displays a civilized and refined demeanor, talking with a regal and eloquent nature. He even utilizes the Keigo dialect in the Japanese versions, which utilizes exceptionally respectful and formal phraseology. In the original and remastered dubs for Dragon Ball Z, while his polite demeanor is somewhat retained (such as his quipping when threatening the Namekians in his introduction that he neglected his manners and should have added 'please' to his threat to them), it also ends up downplayed by emphasizing his more brutal nature. He tends to handle most situations with a systematic approach. He commonly utilizes dark humor, making twisted jokes and tasteless mockery of his foes before killing them. Frieza is fully aware of his reputation for brutality and makes no effort to deny it but instead revels in it as evidenced by his introduction to the Namekians. Likewise, he has shown great anger at the idea of his cruel deeds being undone, such as the revival of all his previous victims from the Dragon Balls. Frieza can be best summed up as an intelligent, composed (for the most part), yet extraordinarily sadistic and completely heartless sociopath. His final form's character biography in Dragon Ball: Raging Blast 2 states that Frieza has unparalleled cruelty. He has even been commonly referred to as 'The evilest guy in Universe 7'. In Cooler's Revenge, Goku, when condemning Frieza's own brother Cooler, noted that Frieza was 'filled with hatred.'",
        "While Frieza himself never attempted to kill either his father or brother during his lifetime and will work together with them to deal with threats to their family's reign (as shown in the Trunks Saga, Plan to Eradicate Super Saiyans, and Xenoverse 2), he has hardly any real love or attachment to them, and even scoffs at the notion of reviving his father when Sorbet suggested it in both Resurrection ‘F’ and Dragon Ball Super. This is further shown when Universe 9 Supreme Kai Roh asks why Frieza would willingly betray Universe 7, asking him about any memories or loved ones Frieza may have, Frieza only coldly dismisses him, saying he has no idea what he is talking about, causing Roh to label Frieza a psychopath when discussing the possibility of Frieza joining Team Universe 9 with Sidra. While he has no real love for his family, he is proud of his clan and respected his father during his lifetime, as he took his father's warning about never opposing either Beerus or Majin Buu seriously. While they can work together, Frieza and Cooler have a strong sibling rivalry, and it is implied that they would have come into conflict over control of the universe, were it not for Frieza's defeat on Namek. In Dragon Ball Super: Broly, Frieza is shown to be mildly annoyed when his father affectionately pats him on the back when they are on Planet Vegeta, showing his general dislike for affection, even from his father. Despite this, he does refer to his father as 'loving' when mentioning that Goku was the first time someone other than his parents managed to inflict pain onto his final form, though he may have been using the term sarcastically.",
        "Frieza is shown to be something of a perfectionist, expecting nothing less from his soldiers as any failure in his eyes will be met with extreme punishment if not death. Even more, he has absolutely no qualms with slaughtering his own forces, no matter how loyal to him, simply for being in his way, as seen from when he destroyed Planet Vegeta despite most of his men being within the trajectory, as well as his reason in the Japanese version for executing a soldier before deciding to personally deal with Future Trunks. In addition, in Resurrection ‘F’, when executing Tagoma by shooting him out into space, he also made no attempt at activating the secondary window to save his forces from being sucked into the vacuum of space (with only Sorbet doing so). He also reacts violently to criticism or if his plans either fail or if his pride is abashed. However, in Cooler's Revenge, Frieza is accused by his older brother to be too lazy dealing with things.",
        "At his core, Frieza relishes glory, power, agony, dominance, control, and destruction, as shown in his enjoyment of Planet Vegeta's destruction, as well as his maniacal glee from destroying planets and making his enemies suffer before he kills them. He is one of the most sadistic and megalomaniacal beings in the known universes, without any sympathetic or redeeming traits. Even more, he has an outspoken disdain for such joyful environments. Due to these combining traits, Frieza is more of a malignant narcissist rather than just a psychopath. During his imprisonment in Hell, he found his constant company of stuffed animals, fairies, and angels joyfully and cheerfully dancing and serenading him to be absolute torture, which ultimately turned out to be a fitting eternal punishment for the evil tyrant. Frieza holds a very profoundly cynical view of others, believing everyone to be selfish and untrustworthy as himself. Ironically, Frieza is outspoken against all forms of nobility, finding it an appalling concept. When Kikono states that the Frieza Force are criminals, Frieza retorts by saying that they merely overtake planets to sell them to those who need a new planet, viewing the interactions as transactional and demonstrating how he makes excuses for his malicious crimes and feels no responsibility for his actions.",
        "Frieza's actions have greatly influenced Universe 7's perception of his race, as shown in Xenoverse when a heroic member of his race named Reso says his race being evil is a misconception. Future Zamasu notes in Xenoverse 2 that the Frieza Race is not well-liked, which again is likely due to Frieza and his family's evil actions. Frieza's amoral and selfish nature, even towards his own kind, could be seen when he met his Universe 6 counterpart, Frost. During their first meeting, they seemingly took a liking towards each other, as they both lived for conquest and destruction. Frieza even points out they have several things in common which leads to Frieza and Frost allying. Ultimately, once Frost outlives his usefulness, Frieza betrays Frost and eliminates him from the tournament. By this time, Frieza openly views Frost as an amateur, presumably due to his reliance on deception and sneak attacks. Frieza has been shown to have a strong influence over people, commonly corrupting them and bending them to his will over a long period. The two most notable examples of this corruption are Vegeta and Tagoma, who both have drastically changed demeanors due to Frieza.",
        "Perhaps Frieza's most noteworthy trait is his enormous ego, matched only by his malice and power. Because of his high opinion of himself, he tends to react to any given situation relatively evenly. Accordingly, Frieza is quite confident in his abilities, commonly referring to his foes as lower life-forms such as insects, and often cherishes the opportunity to mock them (e.g., not using his limbs in some fights). For much of his life, Frieza was viewed as among the most powerful beings in the universe, with Lord Beerus and Majin Buu being the only beings he was warned by his father King Cold not to face. As a consequence, Frieza believes no force can challenge his authority. Owing to his arrogance, Frieza generally refrains from fighting his foes. Instead, he relies on his minions to deal with challengers, and only personally confronts his opponents when forced to do so; this is best shown during the events on Planet Namek and after his first revival. Overall, Frieza seems to simultaneously possess a superiority and inferiority complex, as he can quickly be driven over the edge in anger when foes prove able to overpower or even rival him. At the same time, Frieza possesses a competitive nature, enjoying a foe that can endure his power. As an example, he 'congratulates' Goku for hurting him in his true form.",
        "Another consequence of said arrogance is that Frieza never trained once in his life: he is a naturally gifted, phenomenal warrior and his powers are so strong that he had to suppress them in order to control himself. This on the other hand is, arguably, a consequence of his lack of training. In any case, even in a suppressed form, Frieza was one of the most feared creatures in the universe, immensely stronger than almost any other warrior in the galaxy, and able to disintegrate a planet with a single attack. When he decided to train, in four months only, he managed to equalize Goku's powers as a Super Saiyan Blue; also, only by meditating while he was in Hell, he managed to obtain a perfect control on his final form Golden Frieza. Upon his second revival, he has learned from his mistake and trained himself for a decade in a Hyperbolic Time Chamber to obtain Black Frieza.",
        "Frieza arguably desires absolute control more than being viewed as the most powerful being in the universe; this may be illustrated by the events on Planet Namek, as, by that time, he already controlled around 70% of the universe. By the time he fights in the Tournament of Power, he shows little fear around deities and angels. In fact, he slights Zeno, going so far as to address him simply as 'Zeno' without the royal title 'lord'; later in said tournament, he even refers to the deities as 'colorful brats'. In said tournament, he was annoyed by how Zeno and his future counterpart so casually destroy entire universes, whilst vowing one day to overthrow both Zenos. This serves to show that even Frieza's genocidal nature and love of destruction has its limits; that perception is supported by the fact he tends to only destroy on a planetary scale and usually resorts to such extreme measures only when he believes them to be necessary.",
        "Given his ceaselessly opportunistic and unrepentantly malicious intentions, Frieza knew that the Tournament of Power was the perfect chance to manipulate deities and use them to his advantage. When confronted by assassins hired by Sidra and Roh, he ignored Goku's pleas and slaughtered them. Further, Frieza offered his services to Universe 9 if they would revive him. The deities in attendance were disgusted by Frieza's lack of loyalty to his own universe. Roh noted Frieza's detached and destructive nature showed him to be even better suited to serve as a God of Destruction than Sidra.",
        "Despite his evil nature, Frieza can be quite gregarious towards people who treat him with reverence, such as the Ginyu Force, who worship Frieza and exhibit extreme loyalty towards him. In Xenoverse 2, both Beerus and Whis note Frieza's charisma. In the Frieza's Spaceship rift, it is implied he has a unique leadership style, through which he allows his subordinates to fight amongst each other in an attempt to get in his good graces. However, Frieza has shown mercy towards some of his fighters by giving them second chances; one example is when he allows Dodoria and Zarbon to live after being defeated by the Future Warrior (who was working undercover at the time). However, Frieza rarely shows mercy, and such mercy is generally a one-time thing, as he admits he never gives them more chances. He was also capable of sparing even non-fighters if it served him in some way, as evidenced by how he recruited Macki and Oil into his Frieza Force to act as his wait staff. Frieza's leadership style favors the strong, and the in-fighting keeps his soldiers on their toes. Accordingly, his leadership effectively weeds out the weaker members and motivates his staff to become stronger to protect their positions, rank, and lives. He is also capable of sparing his foes, such as when he let Goku and Vegeta be after besting them with his Black Frieza transformation, although in that case it was mostly because he wasn't even planning on dealing with them anyways.",
        "Following his crushing defeat on Namek, Frieza became obsessed with taking his revenge on Goku and his friends. Frieza's desire for retribution is so all-consuming that he is determined to exact revenge by destroying all his nemesis holds dear. Frieza also apparently suffers from a form of PTSD, as he sees hallucinations of Goku, which frightens him. The mere sight of Future Trunks in Super Saiyan form made Frieza noticeably shake in fear, struggling to recompose himself. In his first revival, he was driven to taking revenge on Goku despite his crushing defeats, ignoring Tagoma's sensible response to focus on rebuilding his empire instead of pursuing a seemingly fruitless scheme of revenge. So driven by the trauma of his defeat and the rage building inside, he tortured Tagoma for suggesting he abandon his vengeance. Then, when Gohan chooses to spare Captain Ginyu, he is reminded of Goku's decision to spare Frieza on Namek and begins torturing Gohan with a barrage of Death Beams, even after he was defeated and helpless on the ground. However, by the time he was revived a second time, he appears to have overcome this trauma. To that end, he smirked at Kale ascending to her Legendary Super Saiyan form (and in the manga even expressed complete confidence he could beat her).",
        "For all his arrogance, Frieza does not totally disregard potential threats to his rule, to the point of paranoia. Frieza destroyed nearly the entire Saiyan race once even their low-level warriors showed strength comparable to his elite soldiers. The Saiyans' growing strength made him concerned about the possibility of a revolution and added to his nagging fear of the Super Saiyan legend. Similarly, after his humbling defeat against Goku on Planet Namek, he willingly admits he cannot defeat certain foes, as shown by his refusal to fight Beerus or Majin Buu. Likewise, Frieza is willing to help others defeat common foes. For example, in the Tournament of Power, Frieza repeatedly aided Goku in his ultimate defeat of Jiren, a mortal warrior with power beyond a God of Destruction.",
        "Following his first revival, Frieza's unwavering desire for victory is tempered by a newfound sense of humility and patience; upon learning of Goku's victory over Majin Buu, Frieza puts his revenge on hold to begin training himself, despite his open disdain of such a 'lowly' task. Frieza's drive for supremacy ultimately allowed him to reach vastly greater levels of power, leading him to unlock a new Ultimate Evolution. However, this discovery only serves to bolster Frieza's sense of confidence and blind drive for revenge. Rather than continuing his training to master his new form, Frieza immediately rushed to Earth. Though it is possible Frieza was convinced he could defeat Goku before his lack of mastery over his new form would become a factor, his impatience became his downfall. While Frieza's calculating nature leaves little room for failure, he nevertheless prepares contingency plans, such as destroying host planets to defeat his foe or using his followers to conduct sneak attacks. Ultimately, however, his execution proves sloppy. Nevertheless, his tactical skills are noted to be brilliant by Vegeta in Dragon Ball Legends, after witnessing Frieza enact a plan to eliminate Frost without transforming himself.",
        "By the Tournament of Power, Frieza's long period of mental training seems to have returned him to his previous composed and self-confident self from before his defeat on Planet Namek. Additionally, he corrects his previous mistake and has refined his Golden form to absolute mastery. At the same time, he is shown willing to temporarily put aside his rivalry with his sworn nemesis Goku to aid him in the Tournament of Power in exchange for his full revival. Still, when revived by Fortuneteller Baba for a single day, Frieza and Goku greet each other by punching each other in the gut, showing that while they are technically allies, their animosity towards each other remains. Frieza proves to be just as devious and scheming as before, playing mind games with his new 'allies' by giving the impression that he intended to kill Goku instead of helping him. To that end, Frieza also makes it clear he will not take orders from Goku.",
        "During the Tournament of Power, Frieza develops a measure of respect for Goku. For example, he shows gratefulness for Goku's naïve nature, and fights by the Saiyan warrior's side to take down Jiren, in such perfect synchronization and understanding of each other's techniques that it is enough to shock Vegeta. Similarly, Frieza acknowledges Goku's might, and is seemingly unsurprised by Goku's ascension to his Ultra Instinct Sign state. At Goku's request, Frieza willingly donates energy to the Universe 7 Spirit Bomb, even as Vegeta proves unwilling. Frieza even saves Goku from Jiren by giving the Saiyan enough energy to return to his feet, as he realizes Goku's Ultra Instinct is the best chance of beating Jiren. Frieza also uses it as an excuse to square himself of his debt to Goku.",
        "As previously stated, Frieza proved to be a surprisingly capable tag-team partner during the Tournament of Power. While teaming with Gohan, the two are able to follow each other's lead and come up with an effective battle strategy on several occasions to eliminate troublesome opponents, with Frieza even admitting to enjoying working with Gohan and openly admiring and complimenting Gohan's leadership skills on a few occasions. This respect also appears to have extended to several other members of Team Universe 7 as well. By the end of the Tournament of Power, despite still being openly as evil and selfish as ever, Frieza has come to respect Goku and his allies, and willingly celebrates with them for a little bit as well after being revived by Whis. His growing admiration for the Z-Fighters is shown with the happy flick of his tail at Goku's declaration that he will take him down if he does go back to his evil ways, implying the motivation for his inevitable showdown with Goku may have grown from simple hatred to the spirited joy of being able to fight a warrior who he can regard as his equal, admittedly viewing Goku as 'a rare breed' of fighter. In Broly, he expresses some disappointment upon seeing Goku being easily defeated by Wrathful Broly, appearing to expect Goku to win and then fight himself.",
        "In Broly, Frieza also reveals that he no longer seeks immortality, for his experience in Hell has made him fear the prospect of being left crippled and with no way out. This is interestingly enough one of the few instances where Frieza actually learns from his previous experiences. Similarly, he ordered one of his men to find out how to make a wish with the Dragon Balls of Earth, presumably to avoid a failure similar to that of Planet Namek, acting as another instance of Frieza learning from his past experiences. A third instance can be seen at the end of the movie, where, after being defeated, Frieza decided to just retreat from Earth for the time being rather than risk being killed by Goku (or rather, a fusion of Goku and Vegeta). On a similar note, when unveiling his new Black Frieza form to Goku and Vegeta and explaining the circumstances behind his accessing it, he quickly added that it took a lot of toil on his part during the decade-long training in the Hyperbolic Time Chamber, implying that he learned his mistake from when he first accessed Golden Frieza and made sure to master the form before formally unveiling it to his rivals. At the same time, Frieza is still filled with vanity. As revealed by Berryblue, Frieza is sensitive about his True form's height to the point that Frieza Force soldiers have been executed in the past for daring to call Final Form Frieza short. He appears to have a rather causal relationship with Berryblue and even allows her to comment on his short stature without killing her, implying a form of genuine fondness for his childhood nanny. More to the former, Frieza's insecurity of his height led him to steal the Earth's Dragon Balls to increase his height. At the same time, valuing how people perceive him, Frieza refuses to revert to his weaker yet taller forms to satisfy his vanity. Even more, he planned to make a wish for his True Form to only gain 5 centimeters, to create the illusion that he was still naturally growing while anymore would look unnatural.",
        "Frieza also showed an interest in Broly's power and potential for growth using Paragus as a means to control him at first. However, once Paragus had outlived his usefulness and lost the remote to the Broly Control Mechanism, Frieza, reminded of how Krillin's death triggered Goku's Super Saiyan transformation, decided to use Paragus' death to trigger Broly's anger through tricking Broly by claiming a stray blast killed Paragus. However, his plan backfires as Super Saiyan Broly blindly attacks him after Goku and Vegeta fly by Frieza as they escape to Piccolo's location. Frieza responds angrily to Broly's attack and tries to fight back in his Golden Form but is no match for Broly's might. After leaving Earth in defeat, Frieza, having learned that the defectors Cheelai and Lemo have joined Broly on Vampa, decides not to hunt them down, hoping that they might tame Broly, whom Frieza hopes may one day serve under him, apparently recognizing the Legendary Super Saiyan's potential. This contrasts with his past fear of Super Saiyans that led him to exterminate most of them as he seeks to make Broly his subordinate.",
        "Frieza's end goal is eventually defeating the Omni-Kings and ruling above even them."
    ],
    biography: []
}